name: Hello World

on: [ push, pull_request, workflow_dispatch ]

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: gcc HelloWorld.c

      - name: Run
        run: ./a.out
